import { mkdir, readFile, writeFile } from "node:fs/promises"
import { dirname, resolve } from "node:path"
import { fileURLToPath } from "node:url"
import { stripTypeScriptTypes } from "node:module"
import { frontendSources } from "./frontend-sources.mjs"

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const entries = [
  [["src/backend.ts"], "dist/backend.js"],
  [frontendSources, "dist/frontend.js"],
]

for (const [sourcePaths, outputPath] of entries) {
  const source = (await Promise.all(
    sourcePaths.map((sourcePath) => readFile(resolve(root, sourcePath), "utf8")),
  )).join("\n")
  const output = stripTypeScriptTypes(source, {
    mode: "transform",
    sourceMap: false,
  })
  await mkdir(dirname(resolve(root, outputPath)), { recursive: true })
  await writeFile(
    resolve(root, outputPath),
    `// Generated from ${sourcePaths.join(", ")}. Do not edit this file directly.\n${output}`,
    "utf8",
  )
  console.log(`${sourcePaths.join(" + ")} -> ${outputPath}`)
}
